version: "3"

services:
  traefik:
    image: traefik:latest
    container_name: traefik
    restart: unless-stopped
    security_opt:
      - no-new-privileges=true
    networks:
      - proxy
    ports:
      - 80:80
      - 443:443
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./traefik-data/traefik.yml:/traefik.yml:ro
      - ./traefik-data/acme.json:/acme.json
      - ./traefik-data/configurations:/configurations
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.traefik-secure.entrypoints=websecure"
      - "traefik.http.routers.traefik-secure.rule=Host(`traefik.ululuu.de`)"
      - "traefik.http.routers.traefik-secure.middlewares=middlewares-secure-headers@file,middlewares-rate-limit@file,chain-oauth@file"
      - "traefik.http.routers.traefik-secure.service=api@internal"

  portainer:
    image: portainer/portainer-ce:latest
    container_name: portainer
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    networks:
      - proxy
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./portainer-data:/data
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=proxy"
      - "traefik.http.routers.portainer-secure.entrypoints=websecure"
      - "traefik.http.routers.portainer-secure.rule=Host(`portainer.ululuu.de`)"
      - "traefik.http.routers.portainer-secure.middlewares=chain-oauth@file"
      - "traefik.http.routers.portainer-secure.service=portainer-svc"
      - "traefik.http.services.portainer-svc.loadbalancer.server.port=9000"

# Google OAuth - Single Sign On using OAuth 2.0 for Traefik 2.2
  oauth:
    container_name: oauth
    image: thomseddon/traefik-forward-auth:latest
    restart: unless-stopped
    networks:
      - proxy
    security_opt:
      - no-new-privileges=true
    environment:
      - CLIENT_ID=911317711309-pc7elr169qpolko3bpa11fpcnhsn8r7d.apps.googleusercontent.com
      - CLIENT_SECRET=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
      - SECRET=bc24554ba1fc4cbfbb3400e906db1c96
      - COOKIE_DOMAIN=ululuu.de
      - INSECURE_COOKIE=false
      - AUTH_HOST=oauth.ululuu.de
      - URL_PATH=/_oauth
      - WHITELIST=marco.janker@gmail.com
      - LOG_LEVEL=debug
      - LOG_FORMAT=text
      - LIFETIME=2592000 # 30 days
      - DEFAULT_ACTION=auth
      - DEFAULT_PROVIDER=google
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=proxy"
      ## HTTP Routers
      - "traefik.http.routers.oauth-secure.entrypoints=websecure"
      - "traefik.http.routers.oauth-secure.rule=Host(`oauth.ululuu.de`)"
      - "traefik.http.routers.oauth-secure.middlewares=chain-oauth@file"
      - "traefik.http.routers.oauth-secure.service=oauth-svc"
      ## HTTP Services
      - "traefik.http.services.oauth-svc.loadbalancer.server.port=4181"

networks:
  proxy:
    external: true
